plugins {
    id("boilerplate.android.application.compose")
    id("boilerplate.hilt")
}

android {
    namespace = "com.kojo.boilerplate"

    defaultConfig {
        applicationId = "com.kojo.boilerplate"
        versionCode = 1
        versionName = "1.0.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }
}

// Phase 0 item 4. `scripts/verify-apk.sh` asserts that the assembled APK carries the package,
// versionCode, versionName, minSdk and targetSdk it is supposed to. Those expectations are
// written out of the build DSL here rather than copied into the script, so there is exactly one
// source of truth: a change to `defaultConfig` moves the expectation with it, and the check keeps
// verifying that AGP actually propagated the declared values into the artifact instead of
// comparing two hand-maintained copies.
//
// The values are read at configuration time and captured as task inputs, so the task stays
// configuration-cache compatible and re-runs when any of them changes.
val debugApkIdentityFile = layout.buildDirectory.file("apk-identity/debug.properties")

tasks.register("writeDebugApkIdentity") {
    description = "Writes the expected identity of the debug APK for scripts/verify-apk.sh."
    group = "verification"

    val debugBuildType = android.buildTypes.getByName("debug")
    // The debug variant's applicationId and versionName are the defaults plus whatever suffix
    // the build type declares. Neither is set today; reading them anyway means adding one later
    // does not silently turn this check into a false failure.
    val applicationId =
        requireNotNull(android.defaultConfig.applicationId) {
            "android.defaultConfig.applicationId is not set"
        } + (debugBuildType.applicationIdSuffix ?: "")
    val versionName =
        requireNotNull(android.defaultConfig.versionName) {
            "android.defaultConfig.versionName is not set"
        } + (debugBuildType.versionNameSuffix ?: "")
    val versionCode =
        requireNotNull(android.defaultConfig.versionCode) {
            "android.defaultConfig.versionCode is not set"
        }
    val minSdk =
        requireNotNull(android.defaultConfig.minSdk) { "android.defaultConfig.minSdk is not set" }
    val targetSdk =
        requireNotNull(android.defaultConfig.targetSdk) {
            "android.defaultConfig.targetSdk is not set"
        }

    inputs.property("applicationId", applicationId)
    inputs.property("versionName", versionName)
    inputs.property("versionCode", versionCode)
    inputs.property("minSdk", minSdk)
    inputs.property("targetSdk", targetSdk)
    outputs.file(debugApkIdentityFile)

    doLast {
        val destination = debugApkIdentityFile.get().asFile
        destination.parentFile.mkdirs()
        destination.writeText(
            """
            # Generated by :app:writeDebugApkIdentity — do not edit.
            applicationId=$applicationId
            versionCode=$versionCode
            versionName=$versionName
            minSdk=$minSdk
            targetSdk=$targetSdk
            """.trimIndent() + "\n",
        )
    }
}

/*
 * The assembly point, and the only module that may see everything.
 *
 * Two kinds of dependency are in this list and they are worth telling apart. `:feature:*`,
 * `:core:ui` and `:core:navigation` are here because this module's own code calls into them —
 * `AppNavHost` names every screen and every route. `:data` is here for the opposite reason:
 * nothing in `src/main` references a single type from it. It is on the list so that its Hilt
 * modules reach the component, which is what turns the interfaces the features inject into
 * objects at runtime. Removing it compiles and then fails at launch with a missing binding, so
 * it is deliberately not a dependency anyone should tidy away.
 */
dependencies {
    implementation(project(":core:auth"))
    implementation(project(":core:common"))
    implementation(project(":core:domain"))
    implementation(project(":core:navigation"))
    implementation(project(":core:ui"))
    implementation(project(":data"))

    implementation(project(":feature:home"))
    implementation(project(":feature:profile"))
    implementation(project(":feature:scanner"))
    implementation(project(":feature:signin"))
    implementation(project(":feature:textrecognition"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.material.icons.extended)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.kotlinx.collections.immutable)

    // WorkManager reaches `:app` for one reason: `BoilerplateApp` has to implement
    // `Configuration.Provider` and hand WorkManager the `HiltWorkerFactory`, because a worker
    // with constructor dependencies cannot be built by the default factory. That is a statement
    // about how the *application* is configured, so it belongs to the application module — and
    // it is the only WorkManager type named outside `:data`. The schedule itself, the worker and
    // the request stay there, behind `BackgroundSyncScheduler`.
    implementation(libs.androidx.work.runtime.ktx)
    implementation(libs.androidx.hilt.work)

    // Test-only on purpose. `StabilityContractTest` needs the Kotlin declaration model — `val`
    // vs `var`, sealed subclasses, generic type arguments — none of which survives into Java
    // reflection. Shipping it in the app would add ~1.7 MB to the APK to answer a question only
    // the build asks.
    testImplementation(libs.kotlin.reflect)
}
