#!/usr/bin/env bash
#
# Tests for scripts/verify-upload-signing.sh.
#
# That script is itself a test — it rehearses the release signing path against a throwaway key —
# and its happy path runs on every CI build. What does not run is any of its failure paths, and
# those are the whole point: a rehearsal that would pass a build wired to no signing config, or one
# that prints a password into a log, is worse than no rehearsal, because it reports green about the
# thing it stopped checking.
#
# So this drives the real script against a stub `gradlew` and a stub `keytool` whose output is
# fixture-controlled, and shows each check failing when it should and only when it should.
#
# It needs nothing but bash: no Gradle, no Android SDK, no JDK, no network. That is deliberate.
# Neither the Android SDK nor the Android Gradle Plugin can be fetched in the environment this
# repository's scheduled agent runs in — Google Maven answers 403 on CONNECT there — so none of the
# five gates in CLAUDE.md can run, and this keeps the gate's own logic checkable anyway.
#
# Usage: scripts/verify-upload-signing.test.sh

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERIFY="$SCRIPT_DIR/verify-upload-signing.sh"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

tests_run=0
tests_failed=0

# The certificate the stub keytool reports for the throwaway key, and the one it reports for the
# debug key. Different, because the point of the `minified` check is that the two are not the same.
THROWAWAY_SHA='AA:BB:CC:DD:EE:FF:00:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF:00:11:22:33:44:55:66:77:88:99'
THROWAWAY_HEX='AABBCCDDEEFF00112233445566778899AABBCCDDEEFF00112233445566778899'
DEBUG_SHA='11:22:33:44:55:66:77:88:99:00:11:22:33:44:55:66:77:88:99:00:11:22:33:44:55:66:77:88:99:00:11:22'

BIN="$WORK/bin"
mkdir -p "$BIN"

# --- stub toolchain ------------------------------------------------------------------------

# Answers `-genkeypair` by creating the file at `-keystore`, and `-list` from a fixture. Both
# exit statuses come from the fixture, so "keytool is broken" is a case like any other.
cat >"$BIN/keytool" <<'STUB'
#!/usr/bin/env bash
mode=list
keystore=
previous=
for argument in "$@"; do
    case "$previous" in -keystore) keystore="$argument" ;; esac
    case "$argument" in -genkeypair) mode=genkeypair ;; esac
    previous="$argument"
done
if [ "$mode" = genkeypair ]; then
    printf 'stub keystore\n' >"$keystore"
    exit "$(cat "$FIXTURE/keytool.genkeypair.exit" 2>/dev/null || echo 0)"
fi
cat "$FIXTURE/keytool.list.out" 2>/dev/null
exit "$(cat "$FIXTURE/keytool.list.exit" 2>/dev/null || echo 0)"
STUB

# Answers the nth invocation from `gradle.<n>.out` and `gradle.<n>.exit`, so a scenario is
# expressed purely as data. The `leak` flag makes it print the password it was handed, which is the
# only way to show that the check for one can fail: the password is generated by the script under
# test and nothing here knows it in advance.
cat >"$BIN/gradlew" <<'STUB'
#!/usr/bin/env bash
count="$(cat "$FIXTURE/calls" 2>/dev/null || echo 0)"
count=$((count + 1))
printf '%s\n' "$count" >"$FIXTURE/calls"
if [ -f "$FIXTURE/leak" ]; then
    printf 'FAILURE: Build failed with an exception: storePassword=%s\n' "$UPLOAD_KEYSTORE_PASSWORD"
fi
cat "$FIXTURE/gradle.$count.out" 2>/dev/null
exit "$(cat "$FIXTURE/gradle.$count.exit" 2>/dev/null || echo 0)"
STUB

chmod +x "$BIN/keytool" "$BIN/gradlew"

# --- baseline fixture: everything wired, gated and quiet about its secrets --------------------

BASELINE="$WORK/baseline"
mkdir -p "$BASELINE"

# The two lines the real keytool prints under "Certificate fingerprints:". Only SHA256 is read, and
# SHA1 is here because it is the line immediately above it and a sloppier pattern would take it.
cat >"$BASELINE/keytool.list.out" <<EOF
Alias name: rehearsal-upload-key-not-a-real-key
Creation date: 1 Jan 2026
Entry type: PrivateKeyEntry
Certificate fingerprints:
	 SHA1: 00:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF:00:11:22:33
	 SHA256: $THROWAWAY_SHA
Signature algorithm name: SHA256withRSA
EOF

# 1 and 2: the release lifecycle task graphs, which have to contain the gate.
for task in assembleRelease bundleRelease; do
    cat >"$BASELINE/gradle.$(if [ "$task" = assembleRelease ]; then echo 1; else echo 2; fi).out" <<EOF
:app:checkUploadSigning SKIPPED
:app:compileReleaseKotlin SKIPPED
:app:$task SKIPPED
EOF
done

# 3: the debug graph, which must not.
cat >"$BASELINE/gradle.3.out" <<'EOF'
:app:compileDebugKotlin SKIPPED
:app:packageDebug SKIPPED
:app:assembleDebug SKIPPED
EOF

# 4: no key declared.
cat >"$BASELINE/gradle.4.out" <<'EOF'
> Task :app:checkUploadSigning FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkUploadSigning'.
> Release signing is not configured: gradle/upload-signing.properties declares no upload key.

  A release built without it would not fail: AGP would write an unsigned artifact and exit 0.
EOF
echo 1 >"$BASELINE/gradle.4.exit"

# 5: the key declared and present — the gate passing, and signingReport's per-variant blocks.
cat >"$BASELINE/gradle.5.out" <<EOF
> Task :app:checkUploadSigning
Play upload signing: alias \`rehearsal-upload-key-not-a-real-key\`, certificate SHA-256 $THROWAWAY_HEX

> Task :app:signingReport
Variant: debug
Config: debug
Store: /home/runner/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
SHA1: 00:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF:00:11:22:33
SHA-256: $DEBUG_SHA
Valid until: Tuesday, 1 January 2055
----------
Variant: release
Config: release
Store: /home/runner/work/app/build/signing/upload-keystore.jks
Alias: rehearsal-upload-key-not-a-real-key
MD5: 11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11
SHA1: FF:EE:DD:CC:BB:AA:99:88:77:66:55:44:33:22:11:00:FF:EE:DD:CC
SHA-256: $THROWAWAY_SHA
Valid until: Sunday, 1 January 2053
----------
Variant: minified
Config: debug
Store: /home/runner/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
SHA1: 00:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF:00:11:22:33
SHA-256: $DEBUG_SHA
Valid until: Tuesday, 1 January 2055
----------
EOF

# 6: a declaration naming another key.
cat >"$BASELINE/gradle.6.out" <<EOF
> Task :app:checkUploadSigning FAILED

FAILURE: Build failed with an exception.
> The keystore in UPLOAD_KEYSTORE_BASE64 is not the key this commit declares.
    declared in gradle/upload-signing.properties: BABBCCDDEEFF00112233445566778899AABBCCDDEEFF00112233445566778899
    in the keystore: $THROWAWAY_HEX
  Signing with the wrong key is the one signing mistake Play cannot undo: an upload it does not
  recognise is rejected outright.
EOF
echo 1 >"$BASELINE/gradle.6.exit"

# 7: the wrong key password.
cat >"$BASELINE/gradle.7.out" <<'EOF'
> Task :app:checkUploadSigning FAILED

FAILURE: Build failed with an exception.
> UPLOAD_KEY_PASSWORD does not open the key `rehearsal-upload-key-not-a-real-key`.
EOF
echo 1 >"$BASELINE/gradle.7.exit"

# --- harness -------------------------------------------------------------------------------

# Runs verify-upload-signing.sh against a private copy of the baseline fixture, after applying the
# caller's mutation to it, and asserts the exit status and that the output names the problem.
#
# Each case runs in a directory of its own, not in the repository: the script writes its keystore
# and its transcript under `app/build/`, relative to wherever it is invoked.
expect() {
    local name="$1" want_status="$2" want_output="$3" mutate="$4"
    tests_run=$((tests_run + 1))

    local fixture="$WORK/case"
    rm -rf "$fixture"
    cp -r "$BASELINE" "$fixture"
    ( cd "$fixture" && eval "$mutate" )

    local sandbox="$WORK/sandbox"
    rm -rf "$sandbox"
    mkdir -p "$sandbox/app/build"

    local output status
    output="$(
        cd "$sandbox" &&
            FIXTURE="$fixture" PATH="$BIN:$PATH" \
                bash "$VERIFY" "$BIN/gradlew" 2>&1
    )"
    status=$?

    if [ "$status" -ne "$want_status" ]; then
        printf 'FAIL  %s: exit %d, expected %d\n%s\n\n' "$name" "$status" "$want_status" "$output"
        tests_failed=$((tests_failed + 1))
        return
    fi
    if [ -n "$want_output" ] && ! printf '%s\n' "$output" | grep -qF "$want_output"; then
        printf 'FAIL  %s: output did not mention %s\n%s\n\n' "$name" "$want_output" "$output"
        tests_failed=$((tests_failed + 1))
        return
    fi
    printf 'ok    %s\n' "$name"
}

# --- cases -----------------------------------------------------------------------------------

expect 'a correctly wired signing path passes' 0 'wired, gated and leak-free' 'true'

expect 'a keytool that cannot generate a key is a usage error' 2 'could not generate' \
    'echo 1 >keytool.genkeypair.exit'
expect 'a keytool that prints no SHA-256 is a usage error' 2 'could not read' \
    "sed -i '/SHA256:/d' keytool.list.out"

# The wiring. This is the assertion the gate rests on: without it, AGP's answer to a release
# variant with no signing config is an unsigned artifact and exit 0.
expect 'a release assemble that does not depend on the gate is caught' 1 \
    'assembleRelease depends on checkUploadSigning' \
    "sed -i '/checkUploadSigning/d' gradle.1.out"
expect 'a bundle that does not depend on the gate is caught' 1 \
    'bundleRelease depends on checkUploadSigning' \
    "sed -i '/checkUploadSigning/d' gradle.2.out"
expect 'a debug build dragged behind the gate is caught' 1 \
    'assembleDebug depends on checkUploadSigning' \
    "sed -i '1i :app:checkUploadSigning SKIPPED' gradle.3.out"
expect 'a release graph that cannot be planned at all is caught' 1 'could not even be planned' \
    'echo 1 >gradle.1.exit'

# The gate itself.
expect 'a gate that passes with no key declared is caught' 1 'passed with no upload key' \
    'echo 0 >gradle.4.exit'
expect 'a gate whose message does not say what to edit is caught' 1 'names the file to edit' \
    "sed -i 's/declares no upload key/is unhappy/' gradle.4.out"
expect 'a gate that rejects its own declared key is caught' 1 'rejected a key that matches' \
    'echo 1 >gradle.5.exit'
expect 'a gate that logs no fingerprint is caught' 1 'reports the alias and the fingerprint' \
    "sed -i '/Play upload signing:/d' gradle.5.out"

# Which key each variant would actually be signed with.
expect 'a release variant signed with another key is caught' 1 'the release variant reports' \
    "sed -i 's/^SHA-256: $THROWAWAY_SHA/SHA-256: 99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99:99/' gradle.5.out"
# The one-line deletion in app/build.gradle.kts that would put the upload key into the shrunk
# build CI publishes as an artifact.
expect 'a minified variant that inherited the upload key is caught' 1 'the minified variant reports' \
    "awk '/^Variant: minified/{m=1} m && /^SHA-256: /{sub(/SHA-256: .*/, \"SHA-256: $THROWAWAY_SHA\")} {print}' gradle.5.out >tmp && mv tmp gradle.5.out"
expect 'a signingReport with no debug variant is caught' 1 'no certificate for the debug variant' \
    "sed -i 's/^Variant: debug/Variant: debugAndroidTest/' gradle.5.out"

# The fingerprint comparison, which is the reason the declaration is checked in at all.
expect 'a gate that accepts a mismatched fingerprint is caught' 1 'accepted a keystore that is not' \
    'echo 0 >gradle.6.exit'
expect 'a mismatch message with only one fingerprint in it is caught' 1 'prints the fingerprint it found' \
    "sed -i \"/in the keystore: /d\" gradle.6.out"

# The passwords.
expect 'a gate that accepts a wrong key password is caught' 1 'accepted a key password' \
    'echo 0 >gradle.7.exit'
expect 'a failure that does not name the variable is caught' 1 'names the variable' \
    "sed -i 's/UPLOAD_KEY_PASSWORD/Something/' gradle.7.out"
expect 'a password printed into the build log is caught' 1 'password appears in' \
    'touch leak'

# Every check runs even after an earlier one fails, so one CI round trip reports the whole
# picture rather than the first problem only.
expect 'multiple failures are all reported' 1 '3 check(s) failed' \
    "sed -i '/checkUploadSigning/d' gradle.1.out
     echo 0 >gradle.4.exit
     echo 0 >gradle.7.exit"

# --- result ------------------------------------------------------------------------------------

printf '\n%d test(s), %d failure(s)\n' "$tests_run" "$tests_failed"
[ "$tests_failed" -eq 0 ]
